name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  flutter_test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version-file: .flutter_version
      - name: Create .env file
        run: |
          echo "EL_API_KEY=${{ secrets.EL_API_KEY}}" >> .env
      - name: Check Flutter Version
        run: flutter --version
      - name: Get Dependencies
        run: flutter pub get
      - name: Analyze Code
        run: flutter analyze
      - name: Run Tests
        run: flutter test

  build_android:
    name: Build Android APK
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version-file: .flutter_version
      - name: Create .env file
        run: |
          echo "EL_API_KEY=${{ secrets.EL_API_KEY}}" >> .env
      - name: Check Flutter Version
        run: flutter --version
      - name: Clean Project
        run: flutter clean
      - name: Get Dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk

  build_ios:
    name: Build iOS App
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version-file: .flutter_version
      - name: Create .env file
        run: |
          echo "EL_API_KEY=${{ secrets.EL_API_KEY}}" >> .env
      - name: Check Flutter Version
        run: flutter --version
      - name: Clean Project
        run: flutter clean
      - name: Get Dependencies
        run: flutter pub get
      - name: Build App
        run: flutter build ios
